export enum FolioCommonEnumsApplicationStageEnum {
  FillingApp = 'filling_app',
  AppInReview = 'app_in_review',
  AwaitingTm = 'awaiting_tm',
  TmRegistered = 'tm_registered',
}

export enum FolioCommonEnumsApplicationStatusEnum {
  RequestInProgress = 'request_in_progress',
  EvaluationInProgress = 'evaluation_in_progress',
  WaitingPayment = 'waiting_payment',
  PaymentFailed = 'payment_failed',
  PaymentCanceled = 'payment_canceled',
  FilingPending = 'filing_pending',
  PreparingApp = 'preparing_app',
  AppDrafted = 'app_drafted',
  ApplicationDraftConfirmed = 'application_draft_confirmed',
  PaymentInProgress = 'payment_in_progress',
  ApplicationFiled = 'application_filed',
  PreliminarilyRefused = 'preliminarily_refused',
  DefendingRefusal = 'defending_refusal',
  OppositionPublished = 'opposition_published',
  ApplicationOpposed = 'application_opposed',
  AppealingAgainstRejection = 'appealing_against_rejection',
  RetrievingConflictingMarks = 'retrieving_conflicting_marks',
  ConflictingMarksRetrieved = 'conflicting_marks_retrieved',
  RetrievalFailed = 'retrieval_failed',
  AdditionalPaymentWaiting = 'additional_payment_waiting',
  AdditionalPaymentFailed = 'additional_payment_failed',
  AdditionalPaymentCancelled = 'additional_payment_cancelled',
  AdditionalPaymentSucceeded = 'additional_payment_succeeded',
  ApplicationRejected = 'application_rejected',
  RegistrationGranted = 'registration_granted',
  RegistrationCompleted = 'registration_completed',
}

export enum FolioCommonEnumsApplicationStepEnum {
  Apply = 'apply',
  PrepReport = 'prep_report',
  AddInfo = 'add_info',
  SendReport = 'send_report',
  ReqReport = 'req_report',
  Contract = 'contract',
  PayWaiting = 'pay_waiting',
  PayExpired = 'pay_expired',
  PayFailed = 'pay_failed',
  PayCanceled = 'pay_canceled',
  FilingPending = 'filing_pending',
  ReqInfoCl = 'req_info_cl',
  ReqInfoAd = 'req_info_ad',
  FilingPrepReport = 'filing_prep_report',
  FilingSendReport = 'filing_send_report',
  FilingResp = 'filing_resp',
  PrepFile = 'prep_file',
  FileDone = 'file_done',
  FileDoneReport = 'file_done_report',
  OaReceive = 'oa_receive',
  OaReceiveReason = 'oa_receive_reason',
  OaReport = 'oa_report',
  OaCaReceive = 'oa_ca_receive',
  OaCaReq = 'oa_ca_req',
  OaCaReport = 'oa_ca_report',
  OaCaNoti = 'oa_ca_noti',
  OppReceive = 'opp_receive',
  OppReport = 'opp_report',
  OppReqInfo = 'opp_req_info',
  OppReqReceive = 'opp_req_receive',
  OppReq = 'opp_req',
  OppReqDone = 'opp_req_done',
  OppReqRedo = 'opp_req_redo',
  OppLose = 'opp_lose',
  OppWin = 'opp_win',
  OppResultReport = 'opp_result_report',
  AppReceive = 'app_receive',
  AppReport = 'app_report',
  AppResultReceive = 'app_result_receive',
  AppLose = 'app_lose',
  AppWin = 'app_win',
  RejectReceive = 'reject_receive',
  RejectReport = 'reject_report',
  RejectCaReceive = 'reject_ca_receive',
  RejectCaReq = 'reject_ca_req',
  Waive = 'waive',
  ReFilingReceive = 're_filing_receive',
  ReFilingDone = 're_filing_done',
  ReFoundReceive = 're_found_receive',
  ReFoundDone = 're_found_done',
  RegReceive = 'reg_receive',
  RegReport = 'reg_report',
  RegDoneReceive = 'reg_done_receive',
  RegDoneReport = 'reg_done_report',
  RegElecReceive = 'reg_elec_receive',
  RegElecReport = 'reg_elec_report',
  CertReceive = 'cert_receive',
  CertSend = 'cert_send',
  CertAnn = 'cert_ann',
  CertAnnDone = 'cert_ann_done',
  AdditionalContract = 'additional_contract',
  AdditionalPayWaiting = 'additional_pay_waiting',
  AdditionalPayExpired = 'additional_pay_expired',
  AdditionalPayFailed = 'additional_pay_failed',
  AdditionalPaySucceeded = 'additional_pay_succeeded',
  AdditionalPayCancel = 'additional_pay_cancel',
}

export const StatusList = {
  [FolioCommonEnumsApplicationStageEnum.FillingApp]: {
    label: 'Filing application',
    value: FolioCommonEnumsApplicationStageEnum.FillingApp,
    children: [
      {
        label: 'Request in progress',
        value: FolioCommonEnumsApplicationStatusEnum.RequestInProgress,
        children: [{ label: '요청 진행중', value: FolioCommonEnumsApplicationStepEnum.Apply }],
      },
      {
        label: 'Evaluation in progress',
        value: FolioCommonEnumsApplicationStatusEnum.EvaluationInProgress,
        children: [
          { label: '보고서 준비', value: FolioCommonEnumsApplicationStepEnum.PrepReport },
          { label: '추가정보 요청', value: FolioCommonEnumsApplicationStepEnum.AddInfo },
          { label: '보고서 송부', value: FolioCommonEnumsApplicationStepEnum.SendReport },
          { label: '조사보고서 답변접수', value: FolioCommonEnumsApplicationStepEnum.ReqReport },
        ],
      },
      {
        label: 'Waiting for payment',
        value: FolioCommonEnumsApplicationStatusEnum.WaitingPayment,
        children: [
          { label: '결제 대기중', value: FolioCommonEnumsApplicationStepEnum.Contract },
          { label: '계좌입금 대기중', value: FolioCommonEnumsApplicationStepEnum.PayWaiting },
        ],
      },
      {
        label: 'Payment failed',
        value: FolioCommonEnumsApplicationStatusEnum.PaymentFailed,
        children: [
          { label: '계좌입금 기한 만료', value: FolioCommonEnumsApplicationStepEnum.PayExpired },
          { label: '결제 실패', value: FolioCommonEnumsApplicationStepEnum.PayFailed },
        ],
      },
      {
        label: 'Payment cancelled',
        value: FolioCommonEnumsApplicationStatusEnum.PaymentCanceled,
        children: [{ label: '결제 취소', value: FolioCommonEnumsApplicationStepEnum.PayCanceled }],
      },
      {
        label: 'Filing pending',
        value: FolioCommonEnumsApplicationStatusEnum.FilingPending,
        children: [{ label: '출원 보류', value: FolioCommonEnumsApplicationStepEnum.FilingPending }],
      },
      {
        label: 'Preparing application',
        value: FolioCommonEnumsApplicationStatusEnum.PreparingApp,
        children: [
          { label: '필요서류 요청', value: FolioCommonEnumsApplicationStepEnum.ReqInfoCl },
          { label: '필요서류 접수', value: FolioCommonEnumsApplicationStepEnum.ReqInfoAd },
          { label: '출원예정보고서 준비', value: FolioCommonEnumsApplicationStepEnum.FilingPrepReport },
        ],
      },
      {
        label: 'Application drafted',
        value: FolioCommonEnumsApplicationStatusEnum.AppDrafted,
        children: [{ label: '출원예정보고서 송부', value: FolioCommonEnumsApplicationStepEnum.FilingSendReport }],
      },
      {
        label: 'Application draft confirmed',
        value: FolioCommonEnumsApplicationStatusEnum.ApplicationDraftConfirmed,
        children: [
          { label: '출원예정보고서 답변접수', value: FolioCommonEnumsApplicationStepEnum.FilingResp },
          { label: '출원지시', value: FolioCommonEnumsApplicationStepEnum.PrepFile },
          { label: '출원완료 접수', value: FolioCommonEnumsApplicationStepEnum.FileDone },
        ],
      },
    ],
  },
  [FolioCommonEnumsApplicationStageEnum.AppInReview]: {
    label: 'Application in review',
    value: FolioCommonEnumsApplicationStageEnum.AppInReview,
    children: [
      {
        label: 'Application filed',
        value: FolioCommonEnumsApplicationStatusEnum.ApplicationFiled,
        children: [
          { label: '출원완료 보고', value: FolioCommonEnumsApplicationStepEnum.FileDoneReport },
          { label: 'OA 접수 (거절 외)', value: FolioCommonEnumsApplicationStepEnum.OaReceive },
          { label: 'OA 접수 (거절이유)', value: FolioCommonEnumsApplicationStepEnum.OaReceiveReason },
        ],
      },
    ],
  },
  [FolioCommonEnumsApplicationStageEnum.AwaitingTm]: {
    label: 'Awaiting trademark',
    value: FolioCommonEnumsApplicationStageEnum.AwaitingTm,
    children: [
      {
        label: 'Preliminarily refused',
        value: FolioCommonEnumsApplicationStatusEnum.PreliminarilyRefused,
        children: [{ label: 'OA 보고', value: FolioCommonEnumsApplicationStepEnum.OaReport }],
      },
      {
        label: 'Defending refusal',
        value: FolioCommonEnumsApplicationStatusEnum.DefendingRefusal,
        children: [
          { label: 'OA 대응 지시접수', value: FolioCommonEnumsApplicationStepEnum.OaCaReceive },
          { label: 'OA 대응 현지지시', value: FolioCommonEnumsApplicationStepEnum.OaCaReq },
          { label: 'OA 대응 현지완료보고', value: FolioCommonEnumsApplicationStepEnum.OaCaReport },
          { label: 'OA 대응완료 고객보고', value: FolioCommonEnumsApplicationStepEnum.OaCaNoti },
        ],
      },
      {
        label: 'Published for opposition',
        value: FolioCommonEnumsApplicationStatusEnum.OppositionPublished,
        children: [
          { label: '출원공고 현지보고접수', value: FolioCommonEnumsApplicationStepEnum.OppReceive },
          { label: '출원공고 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.OppReport },
        ],
      },
      {
        label: 'Application opposed',
        value: FolioCommonEnumsApplicationStatusEnum.ApplicationOpposed,
        children: [
          { label: '이의신청 접수안내', value: FolioCommonEnumsApplicationStepEnum.OppReqInfo },
          { label: '이의신청 답변지시접수', value: FolioCommonEnumsApplicationStepEnum.OppReqReceive },
          { label: '이의신청 답변지시', value: FolioCommonEnumsApplicationStepEnum.OppReq },
          { label: '이의신청 답변완료 보고접수', value: FolioCommonEnumsApplicationStepEnum.OppReqDone },
          { label: '이의신청 재답변접수', value: FolioCommonEnumsApplicationStepEnum.OppReqRedo },
          { label: '이의결정(패) 보고접수', value: FolioCommonEnumsApplicationStepEnum.OppLose },
          { label: '이의결정(승) 보고접수', value: FolioCommonEnumsApplicationStepEnum.OppWin },
          { label: '이의결정 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.OppResultReport },
        ],
      },
      {
        label: 'Appealing against rejection',
        value: FolioCommonEnumsApplicationStatusEnum.AppealingAgainstRejection,
        children: [
          { label: '거절불복심판 청구완료 보고접수', value: FolioCommonEnumsApplicationStepEnum.AppReceive },
          { label: '거절불복심판 청구완료 고객보고', value: FolioCommonEnumsApplicationStepEnum.AppReport },
          { label: '거절불복심판보고 접수', value: FolioCommonEnumsApplicationStepEnum.AppResultReceive },
          { label: '거절불복심판 심결(패) 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.AppLose },
          { label: '거절불복심판 심결(승) 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.AppWin },
        ],
      },
      {
        label: 'Waiting for additional payment',
        value: FolioCommonEnumsApplicationStatusEnum.AdditionalPaymentWaiting,
        children: [
          { label: '추가 결제 대기중', value: FolioCommonEnumsApplicationStepEnum.AdditionalContract },
          { label: '추가 계좌입금 대기중', value: FolioCommonEnumsApplicationStepEnum.AdditionalPayWaiting },
        ],
      },
      {
        label: 'Additional payment failed',
        value: FolioCommonEnumsApplicationStatusEnum.AdditionalPaymentFailed,
        children: [
          { label: '추가 계좌입금 기한 만료', value: FolioCommonEnumsApplicationStepEnum.AdditionalPayExpired },
          { label: '추가 결제 실패', value: FolioCommonEnumsApplicationStepEnum.AdditionalPayFailed },
        ],
      },
      {
        label: 'Additional payment canceled',
        value: FolioCommonEnumsApplicationStatusEnum.AdditionalPaymentCancelled,
        children: [{ label: '추가 결제 취소', value: FolioCommonEnumsApplicationStepEnum.AdditionalPayCancel }],
      },
      {
        label: 'Application rejected',
        value: FolioCommonEnumsApplicationStatusEnum.ApplicationRejected,
        children: [
          { label: '거절결정 보고접수', value: FolioCommonEnumsApplicationStepEnum.RejectReceive },
          { label: '거절결정 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.RejectReport },
          { label: '거절결정 대응 지시접수', value: FolioCommonEnumsApplicationStepEnum.RejectCaReceive },
          { label: '거절결정 대응 현지지시', value: FolioCommonEnumsApplicationStepEnum.RejectCaReq },
          { label: '거절대응 포기', value: FolioCommonEnumsApplicationStepEnum.Waive },
          { label: '재출원 지시접수', value: FolioCommonEnumsApplicationStepEnum.ReFilingReceive },
          { label: '재출원 완료', value: FolioCommonEnumsApplicationStepEnum.ReFilingDone },
          { label: '환불 지시접수', value: FolioCommonEnumsApplicationStepEnum.ReFoundReceive },
          { label: '환불 완료', value: FolioCommonEnumsApplicationStepEnum.ReFoundDone },
        ],
      },
    ],
  },
  [FolioCommonEnumsApplicationStageEnum.TmRegistered]: {
    label: 'Trademark registered',
    value: FolioCommonEnumsApplicationStageEnum.TmRegistered,
    children: [
      {
        label: 'Registration granted',
        value: FolioCommonEnumsApplicationStatusEnum.RegistrationGranted,
        children: [],
      },
      {
        label: 'Registration completed',
        value: FolioCommonEnumsApplicationStatusEnum.RegistrationCompleted,
        children: [
          { label: '등록완료 보고접수', value: FolioCommonEnumsApplicationStepEnum.RegDoneReceive },
          { label: '등록완료 보고완료', value: FolioCommonEnumsApplicationStepEnum.RegDoneReport },
          { label: '등록 완료 & 전자등록증 보고접수', value: FolioCommonEnumsApplicationStepEnum.RegElecReceive },
          { label: '등록완료 & 전자등록증 고객보고완료', value: FolioCommonEnumsApplicationStepEnum.RegElecReport },
          { label: '등록증 접수', value: FolioCommonEnumsApplicationStepEnum.CertReceive },
          { label: '등록증 송부', value: FolioCommonEnumsApplicationStepEnum.CertSend },
          { label: '등록공고 보고접수', value: FolioCommonEnumsApplicationStepEnum.CertAnn },
          { label: '등록공고 보고완료', value: FolioCommonEnumsApplicationStepEnum.CertAnnDone },
        ],
      },
    ],
  },
};
